data_file = "public/data.json"
public_dir = "public"
qr_dir = "public/qr"

[verifier]
name = "OpenTensor (Test)"
public_key = "a494bc676de50279ddc7ba2ddc87302efc5ff9846965f3041001bf4b2b5c0912"

[[chains]]
name = "node-subtensor"
rpc_endpoint = "wss://archivelb.nakamoto.opentensor.ai:9943"
color = "#000000"

[chains.github_release]
owner = "opentensor"
repo = "subtensor"
genesis_hash = "0xadcb639cec07168f455d8bd3a43badf1114a414836829f5000e8279f70d4c667"